SRC/BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import Login,Register,activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/',Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('product/', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('add_one/<int:product_id>', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:product_id>', cart_remove_one, name='cart_remove_one'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

SRC/product/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt


app_name = 'product'
urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:slug>', home, name='category_filter'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('search', search_result, name='search_result'),
]

SRC/product/models.py
from django.db import models
from django.urls import reverse
from coupons.models import CashDiscount, PercentageDiscount
from django.utils.html import format_html


class Category(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name="عنوان")
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True, verbose_name='اسلاگ')

    class Meta:
        ordering = ['title']
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def get_absolute_url(self):
        return reverse('accounts:category_list')

    def __str__(self):
        return self.title


class Book(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name='عنوان')
    description = models.TextField(blank=True, verbose_name='توضیحات')
    category = models.ManyToManyField(Category, related_name='categories', verbose_name='دسته بندی')
    author = models.CharField(max_length=200, verbose_name='نویسنده کتاب')
    price = models.PositiveIntegerField(verbose_name='قیمت')
    cover = models.ImageField(upload_to='cover/products/', null=True, blank=True, verbose_name='کاور')
    available = models.BooleanField(default=True, verbose_name='موجودی انبار')
    created = models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت کتاب')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت کتاب')
    slug = models.SlugField(max_length=200, db_index=True, allow_unicode=True, verbose_name='اسلاگ')
    c_discount = models.ForeignKey(CashDiscount, blank=True, null=True, on_delete=models.SET_NULL,
        related_name='discount', verbose_name='تخفیف نقدی')
    p_discount = models.ForeignKey(PercentageDiscount, blank=True, null=True, on_delete=models.SET_NULL,
        related_name='discount', verbose_name='تخفیف درصدی')
    inventory = models.PositiveIntegerField(null=True, blank=True, verbose_name='موجودی انبار ')

    class Meta:
        ordering = ['title']
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتاب ها'
        index_together = [
            ['id', 'slug']
        ]

    @property
    def final_price(self):
        if self.c_discount and self.c_discount.active:
            return self.price - self.c_discount.amount
        elif self.p_discount and self.p_discount.active:
            discount_amount = (self.p_discount.amount / 100) * self.price
            return int(self.price - discount_amount)
        return self.price

    def get_absolute_url(self):
        return reverse('accounts:home')

    def thumbnail_tag(self):
        return format_html('<img width="100" height="100" style="border-radius:5px" src="{}">'.format(self.cover.url))

    thumbnail_tag.short_description = 'عکس'

    def category_to_str(self):
        return ','.join([category.title for category in self.category.all()])

    category_to_str.short_description = 'دسته بندی'

    def __str__(self):
        return self.title

SRC/product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Book
from django.contrib import messages
from django.http import JsonResponse


# Create your views here.


def home(request, slug=None):

    products = Book.objects.filter(available=True)
    categories = Category.objects.all()
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    return render(request, 'index.html', {'products': products, 'categories': categories})


def product_detail(request, slug):
    product = get_object_or_404(Book, slug=slug)

    if product.inventory == 0:
        messages.error(request,f'!موجود نیست')

    return render(request, 'product/product_detail.html', {'product': product})


def search_result(request):
    if request.is_ajax():
        res = None
        series = request.POST.get('series')
        query_set = Book.objects.filter(
            title__istartswith=series) | Book.objects.filter(author__istartswith=series)

        if len(query_set) > 0 and len(series) > 0:
            data = []
            for book in query_set:
                item = {
                    'slug': book.slug,
                    'title': book.title,
                    'author': book.author,
                }
                data.append(item)
            res = data
        else:
            res = '!کتابی یافت نشد'
        return JsonResponse({'data': res})
    return JsonResponse()

SRC/templates/product/product_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{% block title-meta %}
فروشگاه کتاب | جزییات کتاب
{% endblock %} {% endblock  %}

{% block content %}

{% if messages %}
{% for m in  messages %}
<div class="alert alert-danger container " role="alert" style="
                                                text-align:center;width:505px;
                                                " xmlns="http://www.w3.org/1999/html">

{{m}}
</div>
{% endfor %}
{% endif %}

<div style="
            display: flex;
            text-align: right;
            padding: 200px;
            padding-top:100px;
            flex-basis: 500px;
            align-items: center;
            justify-content: center;
            ">
    <div style="padding-right: 15px; padding-top:20px; background-color:#f8f9fa; height:400px">
        <h6 style="color:#6495ED;"> عنوان: {{product.title}} </h6>
        <h6> نویسنده:<small> {{product.author}}</small></h6>

        <hr>
        <h6>{{product.description|safe|striptags}} </h6>

        <hr>

        {% if product.inventory > 0 %}
            <p>:قیمت</p>
            <span style="color:red;">{% if product.c_discount and product.c_discount.active %}
                -   {{product.c_discount.amount}}

            {% elif product.p_discount and product.p_discount.active %}

                %{{product.p_discount.amount}}

            {% endif %}
            </span>

             {% if product.c_discount and product.c_discount.active or product.p_discount and product.p_discount.active %}
             <del>{{product.price}} </del>تومان
             <p>{{product.final_price}} تومان</p>
             {% else %}
             <p>{{product.price}} تومان</p>
             {% endif %}

            <div style="padding-right:10px;
            padding-top:10px">
            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                {% csrf_token %}

                <button type="submit" style="color:#FFFAF0; background-color:#8FBC8F; border: 2px solid #FAF0E6;">
                    افزودن به سبد خرید
                </button>

            </form>
            {% endif %}
        </div>

    </div>

    <div style="display: flex;background-color:#F8F8FF;">
        {% thumbnail product.cover "300x300" as img %}
                  <img src="{{ img.url }}" class="card-img-top" alt="{{ product.title }}"
                       style=" width: 250px; height:400px">
        {% endthumbnail %}
    </div>

</div>


{% endblock %}