SRC/BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import Login,Register,activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/',Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('product/', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import (
    BookList, BookCreate, BookUpdate, BookDelete,
    Profile,
    CategoryList, CategoryCreate, CategoryDelete, CategoryUpdate,
    Report,AddressView,AddressDelete,AddressUpdate
)

app_name = 'accounts'

urlpatterns = [
    path("", BookList.as_view(), name='home'),
    path("book/create", BookCreate.as_view(), name='book_create'),
    path("book/update/<int:pk>", BookUpdate.as_view(), name='book_update'),
    path("book/delete/<int:pk>", BookDelete.as_view(), name='book_delete'),

    path("categories", CategoryList.as_view(), name='category_list'),
    path("category/create", CategoryCreate.as_view(), name='category_create'),
    path("category/update/<int:pk>", CategoryUpdate.as_view(), name='category_update'),
    path("category/delete/<int:pk>", CategoryDelete.as_view(), name='category_delete'),

    path("profile/", Profile.as_view(), name='profile'),

    path('my-address/', AddressView.as_view(), name='my_address'),
    path('<pk>/update', AddressUpdate.as_view(), name='update_address'),
    path('<pk>/delete/', AddressDelete.as_view(), name='delete_address'),
    path('report', Report.as_view(), name='report')
]

SRC/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('add_one/<int:product_id>', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:product_id>', cart_remove_one, name='cart_remove_one'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

SRC/product/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt


app_name = 'product'
urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:slug>', home, name='category_filter'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('search', search_result, name='search_result'),
]

SRC/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title-meta %}
                فروشگاه کتاب
            {% endblock %}
        </title>
        <!-- Favicon-->

        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body style="text-align:right">
        
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">


            <div class="container px-4 px-lg-5">
                {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'accounts:profile' %}">{{user}}</a>
                {% else %}
                <a class="navbar-brand" href="#">فروشگاه کتاب</a>
                {% endif %}
                {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'logout'  %}">خروج</a>
                <a class="navbar-brand" href="{% url 'password_reset'  %}">فراموشی رمز عبور</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'login'  %}">ورود</a>/
                <a class="navbar-brand" href="{% url 'register'  %}">ثبتنام</a>

                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">دسته بندی</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'product:home' %}">همه کتاب ها</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                 {% for category in categories%}
                                <li><a class="dropdown-item"
                                       href="{% url 'product:category_filter' category.slug %}">
                                                {{category.title}}</a></li>
                                {% endfor%}
                            </ul>
                        </li>
                    </ul>

                    <form class="d-flex">
                        
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1">
                                <a href="{% url 'cart:cart_detail' %}">سبد خرید</a>
                            </i>

                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->

        <div class="w-100 text-center">
            <form autocomplete="off" id="search-form" method="post">
                {% csrf_token %}
                <input type="text" id="search-input"  class="p-3 w-50 search mt-4" placeholder="کتاب/نویسنده"
                       style="text-align:right;">
            </form>
            <div id="result-box" class="result-card not-visible">

            </div>
        </div>
        <hr>

        <!-- Section-->
        {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">فروشگاه کتاب</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

        <!-- Core theme JS-->
        <script>
            const sendSearchData = (series)=>{
                $.ajax({
                    type:'POST',
                    url:'{% url "product:search_result" %}',
                    data:{
                        'csrfmiddlewaretoken':csrf,
                        series: series,
                    },
                    success: (res) =>{
                        const data = res.data
                        if(Array.isArray(data)){
                            result_box.innerHTML = "";
                            // display
                            data.forEach(series=>{
                                result_box.innerHTML += `
                                <a href="/product/${series.slug}" class='link'>
                                    <div class="row mt-2 mb-2">
                                        <div class="col-2">
                                            
                                        </div>

                                        <div class="col-10">
                                                <h5>${series.title}</h5>

                                        </div>
                                    </div>
                                </a>
                                `
                            })
                        }else{
                            if(search_input.value.length > 0){
                                result_box.innerHTML = `<b>${data}</b>`
                            }else{
                                result_box.classList.add('not-visible')
                            }
                        }
                    },
                    error:(res)=>{
                        console.log(res);
                    },
                })

            }

            // get search form
            const search_form = document.getElementById('search-form');
            // gt search input
            const search_input = document.getElementById('search-input');

            const result_box = document.getElementById('result-box');

            // csrf token
            const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value;
            
            search_input.addEventListener('keyup',e=>{

                console.log(e.target.value);

                // now when key is up, show the resultbox

                if(result_box.classList.contains('not-visible')){
                    result_box.classList.remove('not-visible');
                }

                // lets get the search results
                sendSearchData(e.target.value);
            });


        </script>

    </body>
</html>

SRC/templates/index.html
{% extends 'base.html' %}
{% block title %}{% block title-meta %}
فروشگاه کتاب | لیست کتاب ها
{% endblock %} {% endblock  %}
{% block content %}
{% load static %}

<section class="py-5">
    <h3 style="text-align:center;">لیست کتاب ها</h3>
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
        
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        {% if product.cover %}
                        <img class="card-img-top" src="{{ product.cover.url }}" alt={{product.title}}
                             style='width:270px; height:250px ' /> {% endif %}
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{product.title}}</h5>
                                <!-- Product price-->

                                {% if product.c_discount and product.c_discount.active or product.p_discount and product.p_discount.active %}
                                <del>{{product.price}} </del>تومان
                                <p>{{product.final_price}} تومان</p>
                                {% else %}
                                {{product.price}} تومان
                                {% endif %}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                    href="{% url 'product:product_detail' product.slug %}">جزییات</a></div>
                        </div>
                    </div>
                </div>
        
                {% endfor%}
            </div>
        </div>


</section>


{% endblock %}