SRC/BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import Login,Register,activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/',Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('product/', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('add_one/<int:product_id>', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:product_id>', cart_remove_one, name='cart_remove_one'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

SRC/order/urls.py
from django.urls import path
from .views import *
from coupons.views import coupon_apply

app_name = 'order'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('<int:order_id>/', order_detail, name='order_detail'),
    path('apply/<int:order_id>/', coupon_apply, name='coupon_apply'),
    path('order_list/', order_list, name='order_list'),

]

SRC/order/models.py
from django.db import models
from django.conf import settings
from product.models import Book
from coupons.models import Coupon
from account.models import Address


# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders'
        , verbose_name='کاربر')

    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='کوپن')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')
    address = models.ForeignKey(Address, on_delete=models.PROTECT, related_name='order_address', blank=True, null=True)

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش ها'

    @property
    def get_total_cost(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.coupon:
            coupon_amount = (self.coupon.amount / 100) * total
            f_total = int(total - coupon_amount)
            if f_total < total:
                return f_total
        return total

    def __str__(self):
        return f'{self.user}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    product = models.ForeignKey(Book, on_delete=models.PROTECT, related_name='order_items', verbose_name='محصول')
    price = models.IntegerField(verbose_name="قیمت")
    quantity = models.PositiveIntegerField(default=1, verbose_name='تعداد')
    date_added = models.DateTimeField(auto_now_add=True)

    def get_cost(self):
        return self.price * self.quantity

    def __str__(self):
        return f'{self.product.title}'

SRC/order/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.decorators import login_required

from account.models import Address
from .models import Order, OrderItem
from cart.cart import Cart
from coupons.forms import CouponForm


from product.models import Book
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


@login_required()
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    form = CouponForm()
    return render(request, 'order/order.html', {'order': order, 'form': form})


# ثبت سفارش از سبد خرید
@login_required()
def order_create(request):
    cart = Cart(request)
    address = Address.objects.get(id=request.POST.get('my_address'))
    order = Order.objects.create(user=request.user)
    order.address = address
    order.save()

    for item in cart:
        obj = Book.objects.get(id=item['id'])
        if item['quantity'] <= obj.inventory:
            obj.inventory = obj.inventory - item['quantity']
            obj.save()
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                quantity=item['quantity'])

            cart.clear()

    return redirect('order:order_detail', order.id)


@login_required()
def order_list(request):
    orders = Order.objects.filter(user=request.user)

    return render(request, 'registration/order_list.html', {'orders': orders})

SRC/templates/order/order.html
{% extends 'base.html' %}
{% block title %}{% block title-meta %}
فروشگاه کتاب | سفارش
{% endblock %} {% endblock  %}
{% block content %}
<div style="text-align:right;">
    <div style="
            background-color:#87CEFA;
            text-align: center;
            padding: 200px;
            padding-top:100px;
            padding-bottom:215px;

            justify-content: center;
            ">
<h2>{{ order.user }} کاربر</h2>
<h3>سفارش شما ثبت شد</h3>
{% if messages %}
      {% for m in  messages %}
      <div class="alert alert-danger" role="alert">{{ m }}</div>
      {% endfor %}
{% endif %}

آدرس:
{{ order.address.country }},
{{ order.address.state }},
{{ order.address.city }},
{{ order.address.detail_address }}


<p style="color:#2F4F4F;">قیمت نهایی:
    {{order.get_total_cost}}</p>
<br>
<form action="{% url 'order:coupon_apply' order.id %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="اعمال">
</form>
        </div>
</div>
{% endblock %}

SRC/templates/order/update_address.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{% block title-meta %}
فروشگاه کتاب | ویرایش آدرس
{% endblock %} {% endblock  %}
{% block content %}
<div class="container wow fadeIn" style="margin-top:50px;">
    <div class="row">
        <div class="col-md-8 mb-4" style="padding-left:350px">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>ویرایش آدرس</h3>

              <div class='hideable_shipping_form'>

               <div class="col-4" style="text-align:right;">
                  {{form.state|as_crispy_field}}
                </div>

                <div class="col-2">
                </div>

                <div class="col-4">
                  {{form.city|as_crispy_field}}
                </div>

                <div class="col-2">
                </div>

                <div class="col-10">
                  {{form.detail_address|as_crispy_field}}
                </div>


                <div class="col-4">
                  {{form.code|as_crispy_field}}
                </div>
                  <div class="col-8">
                </div>
                  <div class="col-4">
                  {{form.phone_number|as_crispy_field}}
                </div>
              </div>

              <button class="btn btn-primary btn-lg btn-block" type="submit">ویرایش </button>
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock content %}