SRC/BookStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import Login,Register,activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/',Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('product/', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import (
    BookList, BookCreate, BookUpdate, BookDelete,
    Profile,
    CategoryList, CategoryCreate, CategoryDelete, CategoryUpdate,
    Report,AddressView,AddressDelete,AddressUpdate
)

app_name = 'accounts'

urlpatterns = [
    path("", BookList.as_view(), name='home'),
    path("book/create", BookCreate.as_view(), name='book_create'),
    path("book/update/<int:pk>", BookUpdate.as_view(), name='book_update'),
    path("book/delete/<int:pk>", BookDelete.as_view(), name='book_delete'),

    path("categories", CategoryList.as_view(), name='category_list'),
    path("category/create", CategoryCreate.as_view(), name='category_create'),
    path("category/update/<int:pk>", CategoryUpdate.as_view(), name='category_update'),
    path("category/delete/<int:pk>", CategoryDelete.as_view(), name='category_delete'),

    path("profile/", Profile.as_view(), name='profile'),

    path('my-address/', AddressView.as_view(), name='my_address'),
    path('<pk>/update', AddressUpdate.as_view(), name='update_address'),
    path('<pk>/delete/', AddressDelete.as_view(), name='delete_address'),
    path('report', Report.as_view(), name='report')
]

SRC/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('add_one/<int:product_id>', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:product_id>', cart_remove_one, name='cart_remove_one'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

SRC/order/urls.py
from django.urls import path
from .views import *
from coupons.views import coupon_apply

app_name = 'order'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('<int:order_id>/', order_detail, name='order_detail'),
    path('apply/<int:order_id>/', coupon_apply, name='coupon_apply'),
    path('order_list/', order_list, name='order_list'),

]

SRC/product/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt


app_name = 'product'
urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:slug>', home, name='category_filter'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('search', search_result, name='search_result'),
]

SRC/cart/models.py
from django.db import models

# Create your models here.

SRC/cart/forms.py
from django import forms

SRC/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from account.models import Address
from .cart import Cart
from product.models import Book
from django.views.decorators.http import require_POST
from django.contrib import messages

# Create your views here.


def detail(request):
    cart = Cart(request)
    item_quantity = [i for i, item in enumerate(cart)]
    if not item_quantity:
        item_quantity = 'empty'

    addresses = None
    if request.user.is_authenticated:
        addresses = Address.objects.filter(user=request.user)

    if not addresses:
        messages.warning(request, f'!آدرسی وجود ندارد')
    for item in cart:
        book = Book.objects.get(slug=item['slug'])

        if item['quantity'] > book.inventory:
            messages.error(request, f'!'
                                    f' کتاب {book.title} '
                                    f' {item["quantity"]} '
                                    f' عدد موجود نیست ')
    context = {
        'addresses': addresses,
        'cart': cart,
        'item_quantity': item_quantity,
    }
    return render(request, 'cart/detail.html', context)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)

    cart.add(product=product)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_add_one(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)

    cart.add_one(product=product)
    return redirect('cart:cart_detail')


def cart_remove_one(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)

    cart.remove_one(product=product)
    return redirect('cart:cart_detail')

SRC/templates/cart/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
{% if messages %}
  {% for m in  messages %}
<div class="alert alert-danger container " role="alert" style="
                                                text-align:center;width:505px;
                                                " xmlns="http://www.w3.org/1999/html">
    {% if m.tags == 'warning' %}
    {{ m }}<br>.برای افزودن آدرس
  <a href="{% url 'accounts:my_address' %}">کلیک</a>
     کنید
    {% else %}
    {{ m }}
   {% endif %}
  </div>

  {% endfor %}
{% endif %}
{% if item_quantity != 'empty' %}


<div class="card container" style="margin-top:50px;margin-bottom:200px;width:1000px;background-color:#FFF0F5;">
<div style="text-align:center; color:#696969">
  <h3><i class="bi bi-cart-fill bi--md"></i>
    سبد خرید
<i class="bi bi-cart-fill bi--md"></i></h3>
</div><hr><br>
<table class="table table-striped table-hover"  style="text-align:center;">

  <thead>
    <tr>
      <th scope="col">حدف</th>
      <th scope="col">قیمت نهایی</th>
      <th scope="col">قیمت بعد از تخفیف</th>
      <th scope="col">قیمت واحد</th>
      <th scope="col">تعداد</th>
      <th scope="col">بروزرسانی</th>
      <th scope="col">عنوان کتاب</th>
      <th scope="col">تصویر</th>
    </tr>
  </thead>
  <tbody>

  {% for item in cart %}
    <tr>
      <td><a href="{% url 'cart:cart_remove' item.product.id %}">کلیک</a></td>

      <td>{{ item.total_price }}</td>
      <td>{{item.price}}</td>
      <td>{{ item.org_price }}</td>
      <td>{{ item.quantity }}</td>
      <td><div style="display: flex;">
          <form action="{% url 'cart:cart_add_one' item.product.id %}" method="POST">
                {% csrf_token %}
            <button type="submit">+</button>
            </form>
          {% if item.quantity > 1 %}


          <form action="{% url 'cart:cart_remove_one' item.product.id %}" method="POST">
                {% csrf_token %}
            <button type="submit">-</button>
            </form>
          {% elif item.quantity == 1 %}
          <form action="{% url 'cart:cart_remove' item.product.id %}" method="POST">
                {% csrf_token %}
            <button type="submit">-</button>
          </form>
            {% endif %}</div>
      </td>

      <td><a href="{% url 'product:product_detail' item.slug %}">{{ item.product }}</a></td>
      <td>
        {% thumbnail item.product.cover "300x300" as img %}
                  <img src="{{ img.url }}" class="card-img-top" alt="{{ item.product }}"
                       style=" width: 100px; height:130px">
        {% endthumbnail %}
      </td>
      <th scope="row">{{ forloop.counter }}</th>
    </tr>
  {% endfor %}
  <tr>
    <td colspan="1"></td>
    <td>مبلغ قابل پرداخت
      <br>
      {{ cart.get_total_price }}</td>

  </tr>

  </tbody>
</table>
{% if not messages and item_quantity != 'empty'%}
    <h6>انتخاب آدرس</h6>
    <form method="POST" class="card-body " action="{% url 'order:order_create'  %}">
         {% csrf_token %}
      <select class="form-select" aria-label="Default select example" name="my_address"
      style="text-align-last:center;">

          {% for ad in addresses %}

          <option value={{ad.id}}> آدرس
            {{forloop.counter}} :
            {{ad.state}}, {{ad.city}}, {{ad.detail_address}}</option>

          {% endfor %}
      </select>

        {% if addresses %}
        <br>
        <button type="submit" class="btn btn-primary">ثبت سفارش</button>
        {% endif %}
    </form>
  {% endif %}
  </div>
{% else %}
<div style="margin-top:400px">
<h3 style="text-align:center">سبد خرید خالی است</h3>
</div>



{% endif %}
{% endblock %}